import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/welcome');
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('deneme@gmail.com');
  await page.getByRole('button', { name: 'go' }).click();
  await page.getByRole('button', { name: 'iconButton' }).click();
  await page.getByRole('link', { name: 'Conferences' }).click();
  await page.getByRole('button', { name: 'iconButton' }).first().click();
  await page.getByTitle('Add conference').click();
  await page.getByRole('textbox', { name: 'Conference name*' }).click();
  await page.getByRole('textbox', { name: 'Conference name*' }).fill('asd');
  await page.getByRole('button', { name: 'Choose date' }).first().click();
  await page.getByRole('gridcell', { name: '4', exact: true }).click();
  await page.getByRole('button', { name: 'Choose date', exact: true }).click();
  await page.getByRole('gridcell', { name: '11' }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Conference type veritabanında mevcut değilConference type\*$/ }).getByLabel('Open').click();
  await page.getByRole('option', { name: 'On site', exact: true }).click();
  await page.locator('div').filter({ hasText: /^Category veritabanında mevcut değilCategory\*$/ }).getByLabel('Open').click();
  await page.getByRole('option', { name: 'Medical', exact: true }).click();
  await page.getByRole('button', { name: 'Devam Et' }).click();
  await page.locator('div').filter({ hasText: /^Conference name$/ }).nth(1).click();
  await page.getByRole('textbox', { name: 'Conference name' }).fill('asd');
  await page.getByRole('textbox', { name: 'Address' }).click();
  await page.getByRole('textbox', { name: 'Address' }).fill('asd');
  await page.locator('div').filter({ hasText: /^Country veritabanında mevcut değilCountry$/ }).getByLabel('Open').click();
  await page.getByRole('option', { name: 'Türkiye' }).click();
  await page.locator('div').filter({ hasText: /^County veritabanında mevcut değilCounty$/ }).getByLabel('Open').click();
  await page.getByRole('listbox', { name: 'County' }).click();
  await page.locator('div').filter({ hasText: /^City veritabanında mevcut değilCity$/ }).getByLabel('Open').click();
  await page.getByRole('option', { name: 'GEBZE', exact: true }).click();
  await page.getByRole('textbox', { name: 'Latitude' }).click();
  await page.getByRole('textbox', { name: 'Latitude' }).fill('6');
  await page.getByRole('textbox', { name: 'Longitude' }).click();
  await page.getByRole('textbox', { name: 'Longitude' }).fill('5');
  await page.getByRole('button', { name: 'Devam Et' }).click();
  await page.getByRole('button', { name: 'add' }).click();
  await page.getByTestId('tbody').getByRole('cell').filter({ hasText: 'Name' }).getByRole('textbox').click();
  await page.getByTestId('tbody').getByRole('cell').filter({ hasText: 'Name' }).getByRole('textbox').fill('asd');
  await page.getByTestId('tbody').getByRole('cell').filter({ hasText: 'Nationality' }).getByRole('textbox').click();
  await page.getByTestId('tbody').getByRole('cell').filter({ hasText: 'Nationality' }).getByRole('textbox').fill('asd');
  await page.getByTestId('tbody').getByRole('cell').filter({ hasText: 'Rating' }).getByRole('textbox').click();
  await page.getByTestId('tbody').getByRole('cell').filter({ hasText: 'Rating' }).getByRole('textbox').fill('2');
  await page.getByRole('checkbox', { name: 'Main Speaker' }).check();
  await page.getByRole('button', { name: 'Kaydı Tamamla' }).click();
  await page.getByTitle('General.Buttons.Refresh').click();
  await page.getByRole('button', { name: 'GÖRÜNTÜLE' }).first().click();
  await page.getByRole('button', { name: 'Düzenle' }).click();
  await page.locator('div').filter({ hasText: /^Konferans TürüKonferans Türü$/ }).getByLabel('Open').click();
  await page.getByRole('option', { name: 'as', exact: true }).click();
  await page.getByRole('button', { name: 'Kaydet' }).click();
  await page.getByRole('button', { name: 'Geri Dön' }).click();
  await page.getByRole('button', { name: 'DELETE' }).first().click();
});